server:
  port: 9092
  servlet:
    context-path: /dicts
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  application:
    name: DICT-SERVER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_dicts
    username: root
    password: root
  output:
    ansi:
      enabled: detect

eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anibaba.dict.model
logging:
  level:
    .com.anibaba.dict.mapper: debug
