server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVICE

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://127.0.0.1:${server.port}/eureka/
